language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t ptrenglish/docker-react -f Dockerfile.dev . 

script:
    - docker run -e CI=true ptrenglish/docker-react npm run test